# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/ForestGumpLite

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/ForestGumpLite

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/ForestGumpLite/CMakeFiles /home/user/ForestGumpLite/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/ForestGumpLite/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ForestGumpLite

# Build rule for target.
ForestGumpLite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ForestGumpLite
.PHONY : ForestGumpLite

# fast build rule for target.
ForestGumpLite/fast:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/build
.PHONY : ForestGumpLite/fast

src/editor/editor.o: src/editor/editor.cpp.o

.PHONY : src/editor/editor.o

# target to build an object file
src/editor/editor.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/editor/editor.cpp.o
.PHONY : src/editor/editor.cpp.o

src/editor/editor.i: src/editor/editor.cpp.i

.PHONY : src/editor/editor.i

# target to preprocess a source file
src/editor/editor.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/editor/editor.cpp.i
.PHONY : src/editor/editor.cpp.i

src/editor/editor.s: src/editor/editor.cpp.s

.PHONY : src/editor/editor.s

# target to generate assembly for a file
src/editor/editor.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/editor/editor.cpp.s
.PHONY : src/editor/editor.cpp.s

src/game/actors/actor.o: src/game/actors/actor.cpp.o

.PHONY : src/game/actors/actor.o

# target to build an object file
src/game/actors/actor.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/actor.cpp.o
.PHONY : src/game/actors/actor.cpp.o

src/game/actors/actor.i: src/game/actors/actor.cpp.i

.PHONY : src/game/actors/actor.i

# target to preprocess a source file
src/game/actors/actor.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/actor.cpp.i
.PHONY : src/game/actors/actor.cpp.i

src/game/actors/actor.s: src/game/actors/actor.cpp.s

.PHONY : src/game/actors/actor.s

# target to generate assembly for a file
src/game/actors/actor.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/actor.cpp.s
.PHONY : src/game/actors/actor.cpp.s

src/game/actors/obstacle.o: src/game/actors/obstacle.cpp.o

.PHONY : src/game/actors/obstacle.o

# target to build an object file
src/game/actors/obstacle.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/obstacle.cpp.o
.PHONY : src/game/actors/obstacle.cpp.o

src/game/actors/obstacle.i: src/game/actors/obstacle.cpp.i

.PHONY : src/game/actors/obstacle.i

# target to preprocess a source file
src/game/actors/obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/obstacle.cpp.i
.PHONY : src/game/actors/obstacle.cpp.i

src/game/actors/obstacle.s: src/game/actors/obstacle.cpp.s

.PHONY : src/game/actors/obstacle.s

# target to generate assembly for a file
src/game/actors/obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/obstacle.cpp.s
.PHONY : src/game/actors/obstacle.cpp.s

src/game/actors/player.o: src/game/actors/player.cpp.o

.PHONY : src/game/actors/player.o

# target to build an object file
src/game/actors/player.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/player.cpp.o
.PHONY : src/game/actors/player.cpp.o

src/game/actors/player.i: src/game/actors/player.cpp.i

.PHONY : src/game/actors/player.i

# target to preprocess a source file
src/game/actors/player.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/player.cpp.i
.PHONY : src/game/actors/player.cpp.i

src/game/actors/player.s: src/game/actors/player.cpp.s

.PHONY : src/game/actors/player.s

# target to generate assembly for a file
src/game/actors/player.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/actors/player.cpp.s
.PHONY : src/game/actors/player.cpp.s

src/game/gameManager.o: src/game/gameManager.cpp.o

.PHONY : src/game/gameManager.o

# target to build an object file
src/game/gameManager.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/gameManager.cpp.o
.PHONY : src/game/gameManager.cpp.o

src/game/gameManager.i: src/game/gameManager.cpp.i

.PHONY : src/game/gameManager.i

# target to preprocess a source file
src/game/gameManager.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/gameManager.cpp.i
.PHONY : src/game/gameManager.cpp.i

src/game/gameManager.s: src/game/gameManager.cpp.s

.PHONY : src/game/gameManager.s

# target to generate assembly for a file
src/game/gameManager.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/gameManager.cpp.s
.PHONY : src/game/gameManager.cpp.s

src/game/scenes/sceneGame.o: src/game/scenes/sceneGame.cpp.o

.PHONY : src/game/scenes/sceneGame.o

# target to build an object file
src/game/scenes/sceneGame.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/scenes/sceneGame.cpp.o
.PHONY : src/game/scenes/sceneGame.cpp.o

src/game/scenes/sceneGame.i: src/game/scenes/sceneGame.cpp.i

.PHONY : src/game/scenes/sceneGame.i

# target to preprocess a source file
src/game/scenes/sceneGame.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/scenes/sceneGame.cpp.i
.PHONY : src/game/scenes/sceneGame.cpp.i

src/game/scenes/sceneGame.s: src/game/scenes/sceneGame.cpp.s

.PHONY : src/game/scenes/sceneGame.s

# target to generate assembly for a file
src/game/scenes/sceneGame.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/scenes/sceneGame.cpp.s
.PHONY : src/game/scenes/sceneGame.cpp.s

src/game/scenes/sceneMainMenu.o: src/game/scenes/sceneMainMenu.cpp.o

.PHONY : src/game/scenes/sceneMainMenu.o

# target to build an object file
src/game/scenes/sceneMainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/scenes/sceneMainMenu.cpp.o
.PHONY : src/game/scenes/sceneMainMenu.cpp.o

src/game/scenes/sceneMainMenu.i: src/game/scenes/sceneMainMenu.cpp.i

.PHONY : src/game/scenes/sceneMainMenu.i

# target to preprocess a source file
src/game/scenes/sceneMainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/scenes/sceneMainMenu.cpp.i
.PHONY : src/game/scenes/sceneMainMenu.cpp.i

src/game/scenes/sceneMainMenu.s: src/game/scenes/sceneMainMenu.cpp.s

.PHONY : src/game/scenes/sceneMainMenu.s

# target to generate assembly for a file
src/game/scenes/sceneMainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/game/scenes/sceneMainMenu.cpp.s
.PHONY : src/game/scenes/sceneMainMenu.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/map/mapManager.o: src/map/mapManager.cpp.o

.PHONY : src/map/mapManager.o

# target to build an object file
src/map/mapManager.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/map/mapManager.cpp.o
.PHONY : src/map/mapManager.cpp.o

src/map/mapManager.i: src/map/mapManager.cpp.i

.PHONY : src/map/mapManager.i

# target to preprocess a source file
src/map/mapManager.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/map/mapManager.cpp.i
.PHONY : src/map/mapManager.cpp.i

src/map/mapManager.s: src/map/mapManager.cpp.s

.PHONY : src/map/mapManager.s

# target to generate assembly for a file
src/map/mapManager.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/map/mapManager.cpp.s
.PHONY : src/map/mapManager.cpp.s

src/util/Collision.o: src/util/Collision.cpp.o

.PHONY : src/util/Collision.o

# target to build an object file
src/util/Collision.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/Collision.cpp.o
.PHONY : src/util/Collision.cpp.o

src/util/Collision.i: src/util/Collision.cpp.i

.PHONY : src/util/Collision.i

# target to preprocess a source file
src/util/Collision.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/Collision.cpp.i
.PHONY : src/util/Collision.cpp.i

src/util/Collision.s: src/util/Collision.cpp.s

.PHONY : src/util/Collision.s

# target to generate assembly for a file
src/util/Collision.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/Collision.cpp.s
.PHONY : src/util/Collision.cpp.s

src/util/OrientedBoundingBox.o: src/util/OrientedBoundingBox.cpp.o

.PHONY : src/util/OrientedBoundingBox.o

# target to build an object file
src/util/OrientedBoundingBox.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/OrientedBoundingBox.cpp.o
.PHONY : src/util/OrientedBoundingBox.cpp.o

src/util/OrientedBoundingBox.i: src/util/OrientedBoundingBox.cpp.i

.PHONY : src/util/OrientedBoundingBox.i

# target to preprocess a source file
src/util/OrientedBoundingBox.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/OrientedBoundingBox.cpp.i
.PHONY : src/util/OrientedBoundingBox.cpp.i

src/util/OrientedBoundingBox.s: src/util/OrientedBoundingBox.cpp.s

.PHONY : src/util/OrientedBoundingBox.s

# target to generate assembly for a file
src/util/OrientedBoundingBox.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/OrientedBoundingBox.cpp.s
.PHONY : src/util/OrientedBoundingBox.cpp.s

src/util/VectorHelper.o: src/util/VectorHelper.cpp.o

.PHONY : src/util/VectorHelper.o

# target to build an object file
src/util/VectorHelper.cpp.o:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/VectorHelper.cpp.o
.PHONY : src/util/VectorHelper.cpp.o

src/util/VectorHelper.i: src/util/VectorHelper.cpp.i

.PHONY : src/util/VectorHelper.i

# target to preprocess a source file
src/util/VectorHelper.cpp.i:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/VectorHelper.cpp.i
.PHONY : src/util/VectorHelper.cpp.i

src/util/VectorHelper.s: src/util/VectorHelper.cpp.s

.PHONY : src/util/VectorHelper.s

# target to generate assembly for a file
src/util/VectorHelper.cpp.s:
	$(MAKE) -f CMakeFiles/ForestGumpLite.dir/build.make CMakeFiles/ForestGumpLite.dir/src/util/VectorHelper.cpp.s
.PHONY : src/util/VectorHelper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ForestGumpLite"
	@echo "... edit_cache"
	@echo "... src/editor/editor.o"
	@echo "... src/editor/editor.i"
	@echo "... src/editor/editor.s"
	@echo "... src/game/actors/actor.o"
	@echo "... src/game/actors/actor.i"
	@echo "... src/game/actors/actor.s"
	@echo "... src/game/actors/obstacle.o"
	@echo "... src/game/actors/obstacle.i"
	@echo "... src/game/actors/obstacle.s"
	@echo "... src/game/actors/player.o"
	@echo "... src/game/actors/player.i"
	@echo "... src/game/actors/player.s"
	@echo "... src/game/gameManager.o"
	@echo "... src/game/gameManager.i"
	@echo "... src/game/gameManager.s"
	@echo "... src/game/scenes/sceneGame.o"
	@echo "... src/game/scenes/sceneGame.i"
	@echo "... src/game/scenes/sceneGame.s"
	@echo "... src/game/scenes/sceneMainMenu.o"
	@echo "... src/game/scenes/sceneMainMenu.i"
	@echo "... src/game/scenes/sceneMainMenu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/map/mapManager.o"
	@echo "... src/map/mapManager.i"
	@echo "... src/map/mapManager.s"
	@echo "... src/util/Collision.o"
	@echo "... src/util/Collision.i"
	@echo "... src/util/Collision.s"
	@echo "... src/util/OrientedBoundingBox.o"
	@echo "... src/util/OrientedBoundingBox.i"
	@echo "... src/util/OrientedBoundingBox.s"
	@echo "... src/util/VectorHelper.o"
	@echo "... src/util/VectorHelper.i"
	@echo "... src/util/VectorHelper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

