//
// Created by fab on 18/11/2018.
//

#ifndef FORESTGUMPLITE_CONSTANTS_H
#define FORESTGUMPLITE_CONSTANTS_H

/*  Screen constants  */

#define PIXEL_SIZE 32

#define SCREEN_SIZE_WIDTH 640
#define SCREEN_SIZE_HEIGHT 512

#define PIXEL_COUNT_HEIGHT SCREEN_SIZE_HEIGHT / PIXEL_SIZE
#define PIXEL_COUNT_WIDTH SCREEN_SIZE_WIDTH / PIXEL_SIZE

#define PI 3.14159265

/* Map constants  */
#define TILE_TREE 1
#define TILE_ROCK 2
#define TILE_BIGTREE 3
#define TILE_BIGROCK 4

#endif //FORESTGUMPLITE_CONSTANTS_H
